Lesson2
timbynce/test-guru pull request #1
Opened 2022-05-13 10:34 UTC by timbynce

Pull request for Test-Guru 0.1.0

2022-05-13 17:39 UTC, VidgarVii requested changes

2022-05-13 17:39 UTC, VidgarVii commented on README.md
> +* List of tests
тут стоит не много абстрагироваться.
Тест
Вопрос
Ответ - которого почему то нет

List of tests вообще не нужен. Потому что ТестЫ уже будет какой-то список. И сущность для этого точно не стоит создавать

2022-05-13 17:39 UTC, VidgarVii commented on README.md
> +* Score (rules of scroing. But i think it's user attribute)
Score выглядит скорей как какой-то атрибут, а не сущность.
А вот результат прохождения теста надо куда-то записывать. И там же можно подсчитать кол-во очков

2022-05-13 17:39 UTC, VidgarVii commented on README.md
> +
еще не хватает Категории (для тестов)

2022-05-13 17:39 UTC, VidgarVii commented on README.md
> +* History of completed test (per user)
не совсем понятно зачем это

2022-05-13 17:39 UTC, VidgarVii commented on config/initializers/version.rb
> +    VERSION = "0.1.0"
"мутабельные" объекты (строки, хэши, массивы) рекомендуется `freeze`-ить, чтобы они были неизменяемыми
в противном случае константу, ссылающуюся на "мутабельный" объект,  можно изменить: `VERSION << '3.14..'`

2022-05-13 17:39 UTC, VidgarVii commented on public/about.html
> +</html>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file

2022-05-13 17:39 UTC, VidgarVii commented on public/about.html
> +<p>Best wishes for my mentors from <a href="https://www.thinknetica.com">www.thinknetica.com</a></p>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2022-05-14 07:26 UTC, timbynce commented on public/about.html
> +</html>
мне кажется, что autosave в редакторе это хорошая идея... :)

2022-05-15 19:18 UTC, merged