Lesson9
timbynce/test-guru pull request #10
Opened 2022-06-12 19:13 UTC by timbynce

2022-06-13 15:39 UTC, VidgarVii requested changes

2022-06-13 15:39 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  # end
зачем нужен этот коммент? Это ведь мусор в коде?

2022-06-13 15:39 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_user, only: [:start]
для 1 экшена колбек не объявляют. Это усложняет код и дебажить будет сложнее

2022-06-13 15:39 UTC, VidgarVii commented on app/helpers/test_passages_helper.rb
> +  end
тут тернанрик хорошо подойдёт
```ruby
test_passage.good_result? ? 'green' : 'red'
```

2022-06-13 15:39 UTC, VidgarVii commented on app/models/test_passage.rb
> +  before_update :next_question, if: -> { answer_ids.present? }
эти два коллбека делают одно и то же по сути
оба устанавливают следующий вопрос
разница лишь в том, что считать следующим вопросом, т.е разница в поиске этого следующего вопроса

(и обрати внимание - оба вызываются с дополнительным условием, на создании или на апдейте)

имеет смысл объединить их в один простой коллбек:

```ruby
before_validation :set_current_question

...

def set_current_question
  self.current_question = next_question
end
```
а всю различающуюся логику поместить уже в метод `next_question`

(коллбеки бывает удобно использовать, но они часто усложняют код и его отладку, если есть возможность не плодить лишние, то ей надо воспользоваться)


вообще с коллбеками нужно осторожно - они не всегда делают то что ты ожидаешь, тогда когда ты ожидаешь ))
бывают ньюансы о которых не догадываешься, особенно при совместной работе нескольких коллбеков и использовании коллбеков с условиями
поэтому если есть возможность упростить коллбеки, то это нужно делать

2022-06-13 15:39 UTC, VidgarVii commented on app/models/test_passage.rb
> +    self.correct_questions += 1 if correct_answer?(answer_ids)
грубый сайд эффект для метода сетера. Если из-за этого будет баг, то дебажить будет оооочченнь сложно

2022-06-13 15:39 UTC, VidgarVii commented on app/models/test_passage.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
у тебя и метод есть answer_ids и параметр так называется. Как тут не запутаться я не понимаю. 
Кстати зачем вообще нужен метод answer_ids?

2022-06-13 15:39 UTC, VidgarVii commented on app/models/test_passage.rb
> +    correct_answers_count = correct_answers.count
эта переменная не используется.

2022-06-13 15:39 UTC, VidgarVii commented on app/models/test_passage.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
answer_ids может быть нил. И тут будет баг. Если юзер не выберет ответ

2022-06-13 15:39 UTC, VidgarVii commented on app/views/answers/_answer.html.erb
> +</li>
No new lina at end of file

2022-06-13 15:39 UTC, VidgarVii commented on config/routes.rb
> +    end
когда всего одна строчка, можно написать
```ruby
post :start, on: :member

2022-06-13 15:39 UTC, VidgarVii commented on app/models/test_passage.rb
> +end
есть методы и переменные которые не используются

2022-06-14 10:47 UTC, timbynce commented on app/models/test_passage.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
Идея была в том, чтобы не использовать везде подряд собаку.

2022-06-14 18:01 UTC, merged