Lesson18
timbynce/test-guru pull request #19
Opened 2022-07-20 20:45 UTC by timbynce

2022-07-21 08:04 UTC, VidgarVii requested changes

2022-07-21 08:04 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
>      end
если в коде появляется elsif, значит тут проблема с абстрагированием. 
О чём может говорить метод expired? О том что тест завершён. А для этого уже есть метод completed?
Стоило расширить данный метод
И опять же. Если тест завершён. Почему мы не должны отправить письмо об этом?

2022-07-21 08:04 UTC, VidgarVii commented on app/javascript/utilites/timer.js
> +        window.location.href = link
я бы скорее не локейшен менял, а засабмитил форму: `form.submit()`
такой вариант менее "хакерский", все идет в русле естественного сценария (сабмит формы > контроллер > модель > контроллер > вьюха)

как раз в модели можно со стороны сервера проверить не истек ли таймер и "завершить" тест (обнулифаить текущий вопрос)
контроллер в этом случае сделает редирект на `result` безо всяких `JS` смен локации

в модели в методе `accept!` таймер уже проверяется, нужно просто добавить механизм "если время истекло - завершить тест" (обнулифаить текущий вопрос)
контроллер в этом случае сделает редирект на `result` безо всяких `JS` смен локации

2022-07-21 08:04 UTC, VidgarVii commented on app/javascript/utilites/timer.js
> +        let link= "https://testgurutimbynce.herokuapp.com/test_passages/" + testId + "/result"
не стоит явно указывать домен tв коде _estgurutimbynce.herokuapp.com._
Ведь отлично работают относительные ссылки.
А домен может поменяться. И опять же как это тестировать локально?

2022-07-21 11:42 UTC, timbynce commented on app/controllers/test_passages_controller.rb
>      end
Изначально я думал делать проверку не на expired?,  а на invalid? (хотя проврека сейчас всего одна и это показалось избыточным). В остальном всецело согласен.

2022-07-25 16:14 UTC, VidgarVii requested changes

2022-07-25 16:14 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +  end
Админ при создании баджа должен выбирать тип правила (Категория/лвл и пр) И параметр правила (Ид категории/лвл уровня и пр.) 
В ДЗ заданы 3 типа правила. Но учти что система должна быть готова к масштабировании. И правил может быть сколько угодно.
Где то типы правил надо складывать без раздутия моделей и классов
тут ошибка в проектировании самой таблицы. При заполнении таблицы у тебя получится почти пусты колонки :level, :category_id, :test_id, :first_try
Такой подход считается очень плохим. Если колонка почти всегда пустая, то скорей всего она не нужна

2022-07-25 16:14 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id, :author_id, :time_to_pass)
1 что тут делает параметр author_id?
2 код для таймера уже должен лежать в мастер ветке

2022-07-25 16:14 UTC, VidgarVii commented on app/controllers/badge_rewards_controller.rb
> +  end
по ТЗ юзер так же должен видеть все доступные баджы

2022-07-25 16:14 UTC, VidgarVii commented on app/models/badge.rb
> +  end
методы предикаты в своём назывании должны содержать знак вопроса

2022-07-25 16:14 UTC, VidgarVii commented on app/models/badge.rb
> +  end
все эти правила по сути часть бизнес логики. Это всё лучше вынести в отдельные классы сервисы, и не хранить эту логику в моделях. Сейчас модель очень перегружена информацией других классов. И сейчас класс является божественным. (это антипаттерн)

2022-07-25 16:14 UTC, VidgarVii commented on app/models/badge.rb
> +end
надо продумать систему, так чтобы увеличение правил не раздувало кодом классы

2022-07-25 16:14 UTC, VidgarVii commented on app/models/test_passage.rb
> +    Badge.all.each do |badge|
модель должна отвечать за работу только своих данных. 
Тут связи с баджами нет. Большая ошибка делегировать бизнес логу выдачи баджей вообще левой модели. Только контроллер может делегировать процессы. И то он сам ни чего не делает. Но хотя контроллеры знают какой объект надо дёргать, чтобы обработать какой-то запрос. У моделей же нет такого права.
Вспоминай урок про сервисы

2022-07-26 18:52 UTC, VidgarVii requested changes

2022-07-26 18:52 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    params.require(:test).permit(:title, :level, :category_id, :author_id, :time_to_pass)
не исправлено

2022-07-26 18:52 UTC, VidgarVii commented on app/services/test_completion_service.rb
> +end
масштабирование класса пока не продумана. Данный класс быстро разбухнет при увеличении правил 
Посмотри всё же это видео. Я тут разбирал со студентом этот урок.
https://www.youtube.com/watch?v=NIHGCPgQkV0
И по пробуй улучшить свой код

2022-07-28 06:39 UTC, merged