Les4
timbynce/test-guru pull request #5
Opened 2022-05-19 08:21 UTC by timbynce

2022-05-19 14:53 UTC, VidgarVii requested changes

2022-05-19 14:53 UTC, VidgarVii commented on app/models/test.rb
> +    tests.each{|t| t.title}
1 вижу что код не был протестирован
2 https://apidock.com/rails/ActiveRecord/Calculations/pluck

2022-05-19 14:53 UTC, VidgarVii commented on app/models/user.rb
> +  end
Создайте инстанс-метод в модели User, который принимает в качестве аргумента значение уровня сложности и **возвращает список всех Тестов**, которые проходит или когда-либо проходил Пользователь на этом уровне сложности

2022-05-19 14:53 UTC, VidgarVii commented on db/seeds.rb
>  Test.destroy_all
как в мастер попал не проверенный код?
сиды надо было сделать в этом ПР

2022-05-20 06:35 UTC, VidgarVii requested changes

2022-05-20 06:35 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins("JOIN categories ON tests.category_id = categories.id")
можно (и рекомендуется)  писать так:
```ruby
joins(...)...
```
т.е. без явного указания объекта у которого вызывается метод
потому что в данном случае объектом является класс `Test` и ему равен `self` внутри класс-метода
по дефолту, при вызове метода без указания объекта он вызывается у `self`, т.е. в текущем варианте как раз у `Test`

2022-05-20 06:35 UTC, VidgarVii commented on app/models/test.rb
> +        .where("categories.title = ?", title)
лучше всего, где это возможно, использовать "хеш-синтаксис" (см. выше ^^) - обычно это лаконичней и легче править
`where(categories: { title: title })`

2022-05-20 06:35 UTC, VidgarVii commented on db/seeds.rb
> +  { title: 'HTML', category_id: 1, level: 1, author_id: 1 },{ title: 'Go', category_id: 3, level: 3, author_id: 1 },
"хардкодить" `id` - не очень хорошая затея
такой "сид" невозможно накатить на существующую базу, ведь там id могут быть заняты другими записями или вовсе отсутствовать
правильней воспользоваться тем, что метод `create` возвращает созданные записи

2022-05-20 06:35 UTC, VidgarVii commented on db/seeds.rb
> +Category.create([
лучше использовать `create!` - метод бросит исключение, если запись не создастся
сразу будет видно, если что-то пошло не так

2022-05-20 19:52 UTC, VidgarVii requested changes

2022-05-20 19:52 UTC, VidgarVii commented on app/models/test.rb
> +  end
у меня сомнения о работоспсобности метода

2022-05-20 19:52 UTC, VidgarVii commented on db/seeds.rb
> +category_backend = Category.create!(title: "Backend")
метод create! может принимать массив. С массивом удобней работать и не надо будет плодить кучу переменных

2022-05-20 19:52 UTC, VidgarVii commented on db/seeds.rb
> +
Очень мало данных. Такие тесты будет не возможно тестировать. Стоит добавить хотя бы по 3-4 вопроса для каждого теста и по 4 ответа к каждому вопросу

2022-05-20 19:52 UTC, VidgarVii commented on db/seeds.rb
> +result_js = Result.create!(passed: false, test_id: test_js.id , user_id: user_for_tests.id)
а вот Result можно и не создавать

2022-05-20 23:38 UTC, timbynce commented on app/models/test.rb
> +  end
Дропнул БД после переделывания seed и прогнал еще раз тест метода:
02:34 $ bin/rails c
Running via Spring preloader in process 282514
Loading development environment (Rails 6.0.5)
2.7.5 :001 > Test.list_by_category("Frontend")
   (1.4ms)  SELECT "tests"."title" FROM "tests" JOIN categories ON tests.category_id = categories.id WHERE "categories"."title" = $1 ORDER BY "tests"."title" DESC  [["title", "Frontend"]]
 => ["Ruby", "JS"] 
2.7.5 :002 > Test.list_by_category("Sports")
   (1.4ms)  SELECT "tests"."title" FROM "tests" JOIN categories ON tests.category_id = categories.id WHERE "categories"."title" = $1 ORDER BY "tests"."title" DESC  [["title", "Sports"]]
 => ["Basketball"]

2022-05-20 23:42 UTC, timbynce commented on db/seeds.rb
> +result_js = Result.create!(passed: false, test_id: test_js.id , user_id: user_for_tests.id)
Не вполне понимаю почему. Мы же должны как-то тестировать свой метод по возврату пройденных тестов.  Мне кажется, что пройденные тесты логично хранить в таблице результатов.

Собственно сам метод:
  def tests_by_level(level)
    Test.joins('JOIN results ON results.test_id = tests.id')
        .where(results: { user_id: id }, tests: { level: level })
  end

Без результатов попытка его выполнить вернет пустоту и отчаяние.
Могу представить, что мы добавляем в модель пользователя некий current_test, но историю все равно логично хранить же в результатах...

2022-05-21 18:44 UTC, merged