Lesson7
timbynce/test-guru pull request #8
Opened 2022-06-02 13:13 UTC by timbynce

2022-06-03 06:55 UTC, VidgarVii requested changes

2022-06-03 06:55 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions
для "облегчения" роутинга рекомендуется использовать (где это возможно и приемлемо) опцию `shallow: true`
Это уменьшит кол-во запросов в контроллере. Упростит код и укоротит http запрос
[вот](http://rusrails.ru/rails-routing#melkoe-vlozhenie) документация на русском

2022-06-03 06:55 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    question = @test.questions.create(question_params)
При создании и обновлении ресурса нужно проверять валидацию, которая была прописана в модели. И если валидация не прошла, то рендерят форму и выводит ошибки(ошибки будем показывать далее по уроку)
По этому тут надо условие записался ли объект в базу?
стандартный подход экшена create такой
```
@question = @test.questions.build(question_params)
if @question.save
  redirect_to @question
else
  render :new
end
```

2022-06-03 06:55 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
здесь и в `question_params` какая-то путанница...
в `question_params` не должен входить `test_id`, этот аттрибут идет в параметрах, но не под ключом `:question`
метод же `question_params` должен возвращать только аттрибуты идущие в параметрах под ключом `:question`
а остальные параметры вопроса как раз должны идти под ключом `:question` (в нашем случае `body`)
поэтому нужно `@test` для этого экшена найти так же, как для индекса и здесь воспользоваться ассоциацией:
```ruby
@test.questions.create(...)
```

2022-06-03 06:55 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found
before_action и rescue_from разные операции по логике. По этому стоит их разделять пустой строкой

2022-06-03 06:55 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    question = @test.questions.find(params[:id])
если запросы повторяются, то лучше их вынести в колбек

2022-06-03 07:46 UTC, timbynce commented on config/routes.rb
> +    resources :questions
Согласен, сначала так и сделал, Но потом прочел в задании: "Просмотр конкретного вопроса теста". Метод show при shallow становится не подходящим под контекст.

2022-06-04 13:19 UTC, VidgarVii requested changes

2022-06-04 13:19 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions
в смысле не подходящим? экшен show всегда возвращает конкретный ресурс. Как это влияет на конечный результат?
shallow экономит ресурсы и он ни как не меняет возвращаемые ресурсы

2022-06-04 13:19 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    if @question.save
тут происходит 2 попытки создания вопроса. Достаточно одной

2022-06-04 13:19 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      render plain: 'Question was successfully added'
согласно REST после создания ресурса принято показывать этот ресурс

2022-06-05 10:25 UTC, VidgarVii requested changes

2022-06-05 10:25 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :find_test, except: [:show, :destroy]
понятней и безопасней будет указывать only

2022-06-05 10:25 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    test = Test.create(test_params)
если добавляем этот контроллер в текущем ПР, то стоит его тоже привести в порядок

2022-06-06 13:20 UTC, merged